import { SegmentInfo } from './types';

export const OM1SegmentDef = {
  name: 'OM1' as const,
  fields: [
  "Sequence Number - Test/Observation Master File",
  "Producer's Service/Test/Observation ID",
  "Permitted Data Types",
  "Specimen Required",
  "Producer ID",
  "Observation Description",
  "Other Service/Test/Observation IDs for the Observation",
  "Other Names",
  "Preferred Report Name for the Observation",
  "Preferred Short Name or Mnemonic for Observation",
  "Preferred Long Name for the Observation",
  "Orderability",
  "Identity of Instrument Used to Perform this Study",
  "Coded Representation of Method",
  "Portable Device Indicator",
  "Observation Producing Department/Section",
  "Telephone Number of Section",
  "Nature of Service/Test/Observation",
  "Report Subheader",
  "Report Display Order",
  "Date/Time Stamp for any change in Definition for the Observation",
  "Effective Date/Time of Change",
  "Typical Turn-Around Time",
  "Processing Time",
  "Processing Priority",
  "Reporting Priority",
  "Outside Site(s) Where Observation may be Performed",
  "Address of Outside Site(s)",
  "Phone Number of Outside Site",
  "Confidentiality Code",
  "Observations required to interpret the Observation",
  "Interpretation of Observations",
  "Contraindications to Observations",
  "Reflex Tests/Observations",
  "Rules that Trigger Reflex Testing",
  "Fixed Canned Message",
  "Patient Preparation",
  "Procedure Medication",
  "Factors that may Affect the Observation",
  "Service/Test/Observation Performance Schedule",
  "Description of Test Methods",
  "Kind of Quantity Observed",
  "Point Versus Interval",
  "Challenge Information",
  "Relationship Modifier",
  "Target Anatomic Site Of Test",
  "Modality Of Imaging Measurement",
  ] as const,
} satisfies SegmentInfo;

export type OM1FieldName = typeof OM1SegmentDef.fields[number];
